[workspace]
authors = ["Anthony Tong <atong28.usa@gmail.com>"]
channels = ["conda-forge"]
name = "MARINABackend"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
# We need a python version that is compatible with pytorch
python = ">=3.11,<3.12"
numpy = ">=2.3.3,<3"
matplotlib = ">=3.10.6,<4"
pandas = ">=2.3.2,<3"
wandb = ">=0.21.1,<0.22"
rdkit = ">=2025.3.6,<2026"
ipython = ">=9.5.0,<10"
jupyter = ">=1.1.1,<2"
ipykernel = ">=6.30.1,<7"
flask = ">=3.1.2,<4"
gunicorn = ">=23.0.0,<24"
plotly = ">=6.3.0,<7"
requests = ">=2.32.5,<3"
tqdm = ">=4.67.1,<5"
flask-caching = ">=2.3.1,<3"
peewee = ">=3.18.2,<4"
flask-login = ">=0.6.3,<0.7"
werkzeug = ">=3.1.3,<4"
flask-cors = ">=6.0.1,<7"
python-lmdb = ">=1.7.5,<2"

[pypi-dependencies]
torch = { version = "==2.7.1", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = "==0.22.1", index = "https://download.pytorch.org/whl/cpu" }
lightning = { version = "==2.5.5" }
